### ISSUE TITLE
`client.use_pool` does not override mount configuration

### ISSUE THREAD

**Issue by arik-shurygin** [CDCgov/cfa_azure#91] opened 2024-06-25 19:17 UTC
in short if you create a pool and mount specific input and output blobs to the node, that mount configuration is locked in place. If in the future you decide to mount new blobs as `input` and `output` the mount configuration of that pool will not change, you must create a new pool with a new name that mounts the different storage blobs.

For an example see: https://portal.azure.com/#view/Microsoft_Azure_Batch/PoolMenuBlade/~/mount-configuration/batchAccountId/%2Fsubscriptions%2Fef340bd6-2809-4635-b18b-7e6583a8803b%2FresourceGroups%2FEXT-EDAV-CFA-PRD%2Fproviders%2FMicrosoft.Batch%2FbatchAccounts%2Fcfaprdba/poolId/scenarios_8cpu_pool

This pool was created by the following commands:

```
client.set_input_container("scenarios-test-container")
client.set_output_container("example-output-scenarios-mechanistic", "output")
client.set_scaling(
    mode="autoscale",
    autoscale_formula_path="secrets/autoscale.txt",
    timeout=TIMEOUT_MINS,
)
client.create_pool(pool_name="scenarios_8cpu_pool")
```

If I try to rerun this script for launching jobs but instead run the following:
```
client.set_input_container("scenarios-mechanistic-input", "input")
client.set_output_container("scenarios-mechanistic-output", "output")
client.set_scaling(
    mode="autoscale",
    autoscale_formula_path="secrets/autoscale.txt",
    timeout=TIMEOUT_MINS,
)
client.use_pool(pool_name="scenarios_8cpu_pool")
```
the new input and output containers will not be mounted to nodes within `scenarios_8cpu_pool` instead, the old ones will be mounted from when the pool was created.

I am unsure if this is expected behavior but this should definitely be documented if so, as there are no warnings that the new `input/output` containers are not being attached.

**Comment by ryanraaschCDC** [comment] 2024-07-01 20:42
This is intended from the way Azure works. However, it might be beneficial to create an `update_pool_settings()` method to account for changes you wish to make to an existing pool. I'll look into how we can update pool settings and I will add a warning in the `use_pool()` method.

**Comment by ryanraaschCDC** [comment] 2024-07-31 22:37
@arik-shurygin I'm starting to look into this issue of updating the pool parameters. I can see us going about this in a couple ways. Let me know which method you prefer:
1. the user uses client.set_blob_container, client. debugging (True), etc. and then runs client.update_pool() to push these changes
2.  the user can specify client.update_pool() whenever and takes various parameters as inputs, like debugging, blob_container_name, etc. It would look something like client.update_pool(debugging, blob_container_name, mode = "autoscale", ...) 

I'm thinking option 2 would be better since it can be part of a workflow or standalone, but I would like your input.

**Comment by arik-shurygin** [comment] 2024-07-31 23:46
> @arik-shurygin I'm starting to look into this issue of updating the pool parameters. I can see us going about this in a couple ways. Let me know which method you prefer:
> 
> 1. the user uses client.set_blob_container, client. debugging (True), etc. and then runs client.update_pool() to push these changes
> 2. the user can specify client.update_pool() whenever and takes various parameters as inputs, like debugging, blob_container_name, etc. It would look something like client.update_pool(debugging, blob_container_name, mode = "autoscale", ...)
> 
> I'm thinking option 2 would be better since it can be part of a workflow or standalone, but I would like your input.

Hey Ryan, yeah option two would work as well. I think the original reason for the ticket was my surprised that once the pool is generated the input and output blobs are fixed and unable to be changed by future jobs run on that same pool. The way that the user explicitly calls `client.set_input_container()` and `client.set_output_container()`  to me makes it feel like resources on any pool can mount to any blob, and a new pool does not need to be created to change the input/output mounts. 

If Azure does not provide functionality to run a job with specific input/output mounts as a one-time thing then this may not be possible.

Either way an easy way to update a pool would still be appreciated since it removes the need to delete the pool on Azure Batch Explorer and then make a new one.

**Comment by xop5** [comment] 2024-09-19 15:43
@arik-shurygin @ryanraaschCDC 
I posted a question to the Azure Batch team on MSDN. A member of that team has confirmed the containers mapped to an Azure batch pool are immutable. We need to create a new pool every time we change the container mapping

https://learn.microsoft.com/en-us/answers/questions/2072111/is-it-possible-to-update-the-autoscaling-formula-a

**Comment by xop5** [comment] 2024-09-27 17:23
Pull request https://github.com/CDCgov/cfa_azure/pull/130 created

**Comment by xop5** [comment] 2024-10-24 15:43
Code was integration tested and merged into master

**Closed by xop5** 2024-10-24 15:43 UTC
